# Netlify configuration for Northern VA Water Damage Authority Reversal Framework™
[build]
  # Build configuration for static site deployment
  publish = "."
  command = "echo 'Static site - no build command needed'"

[build.environment]
  # Node version for any build processes
  NODE_VERSION = "18"

[[headers]]
  # Security headers for all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://connect.facebook.net; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://www.google-analytics.com; frame-src https://www.google.com;"

[[headers]]
  # Cache control for static assets
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Redirect rules for clean URLs and SEO
[[redirects]]
  # Main landing page
  from = "/water-damage"
  to = "/northern-va-water-damage.html"
  status = 301

[[redirects]]
  # Blog section
  from = "/blog"
  to = "/blog-index.html"
  status = 301

[[redirects]]
  # FAQ section
  from = "/faq"
  to = "/northern-va-water-damage-faq.html"
  status = 301

[[redirects]]
  # Emergency contact redirect
  from = "/emergency"
  to = "/northern-va-water-damage.html#emergency"
  status = 301

# 404 fallback to main landing page for emergency situations
[[redirects]]
  from = "/*"
  to = "/northern-va-water-damage.html"
  status = 404

[dev]
  # Local development settings
  port = 8888
  targetPort = 8888
  autoLaunch = false
