# Netlify Configuration Template
[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:8181/api/:splat"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

[[redirects]]
  from = "/mcp/*"
  to = "http://localhost:8051/mcp/:splat"
  status = 200
  force = true
  conditions = {Role = ["admin"]}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"